RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Workshop - Deploying Containers with AWS CDK and React with AWS Amplify"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = false
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

googleAnalytics = "UA-55517703-6"

[params]
  description = "Deploying an Application Backend with Node.js and Frontend with React"
  author = "Uriel Ramirez"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[privacy.youtube]
    disable = false
    privacyEnhanced = true
[privacy.twitter]
    disable = false
    enableDNT = true
    simple = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
[Languages.en]
title = "Workshop - Deploying Containers with AWS CDK and React with AWS Amplify"
weight = 1
languageName = "English"
